# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tuust',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/tuust',
                'lib_path': 'tuust'},
  'syms': {'tuust.core': {'tuust.core.foo': ('core.html#foo', 'tuust/core.py')}}}
